# Generated by Django 5.1.15 on 2026-04-27 22:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Legalizacion',
            fields=[
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Número')),
                ('monto_aprobado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto aprobado')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('fecha_consignacion', models.DateField(blank=True, null=True, verbose_name='Fecha de consignación')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automáticamente: monto_aprobado - sum(valor de gastos). Positivo: a favor de la empresa. Negativo: a favor del empleado.', max_digits=14, verbose_name='Saldo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legalizaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('elaboro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legalizaciones_elaboradas', to=settings.AUTH_USER_MODEL, verbose_name='Elaboró')),
            ],
            options={
                'verbose_name': 'Legalización',
                'verbose_name_plural': 'Legalizaciones',
                'ordering': ['-fecha_solicitud', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente_proveedor', models.CharField(max_length=255, verbose_name='Cliente / Proveedor')),
                ('cedula_nit', models.CharField(max_length=32, verbose_name='Cédula / NIT')),
                ('numero_factura', models.CharField(max_length=64, verbose_name='Número de factura')),
                ('centro_costos', models.CharField(max_length=64, verbose_name='Centro de costos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('legalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='legalizaciones.legalizacion', verbose_name='Legalización')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['fecha', 'creado_en'],
                'indexes': [models.Index(fields=['legalizacion', 'fecha'], name='legalizacio_legaliz_0f8640_idx'), models.Index(fields=['centro_costos'], name='legalizacio_centro__1fe152_idx')],
            },
        ),
    ]
