# Generated by Django 5.1.15 on 2026-04-28 20:40

import django.core.validators
import legalizaciones.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='El IVA no puede ser negativo.')], verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El valor base debe ser mayor a cero.')], verbose_name='Valor base'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='cedula_nit',
            field=models.CharField(max_length=32, validators=[legalizaciones.models.validar_cedula_nit], verbose_name='Cédula / NIT'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automáticamente: valor_base + IVA', max_digits=14, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='legalizacion',
            name='monto_aprobado',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El monto aprobado debe ser mayor a cero.')], verbose_name='Monto aprobado'),
        ),
    ]
