# Generated by Django 5.1.15 on 2026-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0002_add_valor_base_iva_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='archivo_factura',
            field=models.FileField(blank=True, help_text='Foto (JPG/PNG) o PDF de la factura', null=True, upload_to='facturas/%Y/%m/', verbose_name='Archivo factura'),
        ),
    ]
