# Generated by Django 5.1.15 on 2026-04-29 — modificado para backfill

from django.db import migrations, models


def backfill_codigos(apps, schema_editor):
    """
    Asigna un código LC-YYYY-NNN a cada legalización existente,
    ordenando por fecha_solicitud + creado_en para mantener
    la correlatividad cronológica.
    """
    Legalizacion = apps.get_model("legalizaciones", "Legalizacion")

    registros = Legalizacion.objects.filter(codigo="").order_by(
        "fecha_solicitud", "creado_en"
    )

    # Agrupar por año de fecha_solicitud
    contadores = {}
    for leg in registros:
        anio = leg.fecha_solicitud.year
        contadores[anio] = contadores.get(anio, 0) + 1
        leg.codigo = f"LC-{anio}-{contadores[anio]:03d}"
        leg.save(update_fields=["codigo"])


def revertir_codigos(apps, schema_editor):
    Legalizacion = apps.get_model("legalizaciones", "Legalizacion")
    Legalizacion.objects.update(codigo="")


class Migration(migrations.Migration):

    dependencies = [
        ("legalizaciones", "0003_add_archivo_factura_gasto"),
    ]

    operations = [
        # Paso 1: Agregar campo sin restricción UNIQUE (permite blanks temporalmente)
        migrations.AddField(
            model_name="legalizacion",
            name="codigo",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Código legible auto-generado. Formato: LC-YYYY-NNN",
                max_length=20,
                verbose_name="Código",
            ),
        ),
        # Paso 2: Rellenar registros existentes con códigos únicos
        migrations.RunPython(backfill_codigos, revertir_codigos),
        # Paso 3: Ahora sí aplicar restricción UNIQUE
        migrations.AlterField(
            model_name="legalizacion",
            name="codigo",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Código legible auto-generado. Formato: LC-YYYY-NNN",
                max_length=20,
                unique=True,
                verbose_name="Código",
            ),
        ),
    ]
