# Generated by Django 5.1.15 on 2026-04-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0004_add_codigo_legalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='rechazado',
            field=models.BooleanField(default=False, verbose_name='Rechazado'),
        ),
    ]
