# Generated by Django 5.1.15 on 2026-04-29 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0005_add_rechazo_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('DEVUELTO', 'Devuelto para corrección'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=10, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENVIADA', 'Legalización enviada'), ('APROBADA', 'Legalización aprobada'), ('RECHAZADA', 'Legalización rechazada'), ('DEVUELTA', 'Devuelta para corrección'), ('GASTO_RECHAZADO', 'Gasto rechazado')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL de acceso')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('legalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='legalizaciones.legalizacion', verbose_name='Legalización')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['destinatario', 'leida', '-creado_en'], name='legalizacio_destina_93aada_idx')],
            },
        ),
    ]
