# Generated by Django 5.1.15 on 2026-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0006_add_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalizacion',
            name='fecha_cierre',
            field=models.DateField(blank=True, help_text='Fecha de cierre oficial registrada por el aprobador.', null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='legalizacion',
            name='periodo_desde',
            field=models.DateField(blank=True, help_text='Fecha de inicio del período que cubre esta caja menor.', null=True, verbose_name='Período de caja — desde'),
        ),
        migrations.AddField(
            model_name='legalizacion',
            name='periodo_hasta',
            field=models.DateField(blank=True, help_text='Fecha de cierre del período que cubre esta caja menor.', null=True, verbose_name='Período de caja — hasta'),
        ),
    ]
