# Generated by Django 5.1.15 on 2026-05-05 16:01

import django.core.validators
import django.db.models.deletion
import legalizaciones.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0007_add_periodo_caja_y_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de costos',
                'verbose_name_plural': 'Centros de costos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ENVIADA', 'Legalización enviada'), ('APROBADA', 'Legalización aprobada'), ('RECHAZADA', 'Legalización rechazada'), ('DEVUELTA', 'Devuelta para corrección'), ('GASTO_RECHAZADO', 'Gasto rechazado'), ('ALERTA_CIERRE', 'Alerta de cierre próximo'), ('SOL_ENVIADA_AREA', 'Solicitud → Gerencia Área'), ('SOL_APROBADA_AREA', 'Solicitud aprobada por Área'), ('SOL_APROBADA_CORP', 'Solicitud aprobada por Corporativa'), ('SOL_DESEMBOLSADA', 'Caja desembolsada'), ('SOL_RECHAZADA', 'Solicitud rechazada')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('cedula', models.CharField(blank=True, max_length=32, validators=[legalizaciones.models.validar_cedula_nit], verbose_name='Cédula')),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('entidad_bancaria', models.CharField(blank=True, max_length=80)),
                ('numero_cuenta', models.CharField(blank=True, max_length=40)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=10)),
                ('firma_imagen', models.ImageField(blank=True, help_text='Firma reutilizable. Puedes sobreescribirla en cada solicitud.', null=True, upload_to='firmas/perfil/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCaja',
            fields=[
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, editable=False, help_text='SOL-YYYY-NNNN', max_length=20, unique=True)),
                ('numero_caja', models.CharField(blank=True, editable=False, help_text='CAJA-YYYY-NNNN — asignado al crear la solicitud', max_length=20, unique=True)),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('ciudad', models.CharField(max_length=80)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=32, validators=[legalizaciones.models.validar_cedula_nit])),
                ('valor_caja', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Caja por valor de')),
                ('entidad_bancaria', models.CharField(max_length=80)),
                ('numero_cuenta', models.CharField(max_length=40)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PEND_AREA', 'Pendiente Gerencia Área'), ('PEND_CORP', 'Pendiente Gerencia Corporativa'), ('APROBADA', 'Aprobada — lista para desembolso'), ('DESEMBOLSADA', 'Desembolsada'), ('LEGALIZADA', 'Legalizada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('firma_empleado', models.ImageField(blank=True, null=True, upload_to='firmas/empleado/%Y/%m/')),
                ('firma_empleado_fecha', models.DateField(blank=True, null=True)),
                ('firma_area', models.ImageField(blank=True, null=True, upload_to='firmas/area/%Y/%m/')),
                ('firma_area_fecha', models.DateField(blank=True, null=True)),
                ('firma_corp', models.ImageField(blank=True, null=True, upload_to='firmas/corp/%Y/%m/')),
                ('firma_corp_fecha', models.DateField(blank=True, null=True)),
                ('fecha_desembolso', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobador_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprob_area', to=settings.AUTH_USER_MODEL)),
                ('aprobador_corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprob_corp', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de caja',
                'verbose_name_plural': 'Solicitudes de caja',
                'ordering': ['-fecha_solicitud', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('RESTAURANTE', 'Restaurante'), ('PEAJES', 'Peajes'), ('HIDRATACION', 'Hidratación'), ('HOSPEDAJE', 'Hospedaje'), ('OTROS', 'Otros')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('observaciones', models.TextField(blank=True, help_text="Obligatorio cuando el ítem es 'Otros' (justificación).")),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud', to='legalizaciones.centrocosto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='legalizaciones.solicitudcaja')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud',
                'verbose_name_plural': 'Ítems de solicitud',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddField(
            model_name='legalizacion',
            name='solicitud',
            field=models.OneToOneField(blank=True, help_text='Solicitud de caja que originó esta legalización.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalizacion', to='legalizaciones.solicitudcaja', verbose_name='Solicitud de caja'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='legalizaciones.solicitudcaja', verbose_name='Solicitud de caja'),
        ),
        migrations.AddIndex(
            model_name='solicitudcaja',
            index=models.Index(fields=['estado', '-creado_en'], name='legalizacio_estado_3b78e3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcaja',
            index=models.Index(fields=['solicitante', '-creado_en'], name='legalizacio_solicit_b3fefb_idx'),
        ),
    ]
