# Generated by Django 5.1.15 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0009_grupos_gerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcaja',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='solicitudcaja',
            name='numero_caja',
            field=models.CharField(blank=True, editable=False, help_text='CAJA-YYYY-NNNN — asignado automáticamente al crear la solicitud', max_length=20, unique=True, verbose_name='N° de caja'),
        ),
    ]
