# Generated by Django 5.1.15 on 2026-05-06 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0010_solicitud_drop_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='iva_porcentaje',
            field=models.SmallIntegerField(choices=[(0, '0 % — Excluido / Exento'), (5, '5 %'), (19, '19 % — Tarifa general')], default=19, help_text='Tarifa de IVA aplicada. El monto se calcula automáticamente.', verbose_name='% IVA'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado: valor_base × iva_porcentaje / 100', max_digits=14, verbose_name='IVA ($)'),
        ),
    ]
