# Generated by Django 5.1.15 on 2026-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0012_legalizacion_motivo_aprobador'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalizacion',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, help_text='Fecha en que el aprobador aprobó la legalización.', null=True, verbose_name='Fecha de legalización'),
        ),
    ]
