# Generated by Django 5.1.15 on 2026-05-11 18:46

import legalizaciones.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalizaciones', '0013_add_fecha_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='archivo_factura',
            field=models.FileField(blank=True, help_text='Foto (JPG/PNG/WEBP) o PDF de la factura — máx 10 MB', null=True, upload_to='facturas/%Y/%m/', validators=[legalizaciones.validators.validar_archivo_factura], verbose_name='Archivo factura'),
        ),
    ]
